# Generated by Django 2.1.4 on 2019-01-11 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('neirong', models.TextField()),
                ('guanjianzi', models.CharField(max_length=200)),
                ('miaoshu', models.CharField(max_length=200)),
                ('lanmu', models.CharField(max_length=10)),
                ('biaoqian', models.CharField(max_length=500)),
                ('icon', models.ImageField(upload_to='upload')),
                ('move', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Lanmus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_id', models.CharField(max_length=10)),
                ('lanmu', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lanmus',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='lanmus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Lanmus'),
        ),
    ]
