# Generated by Django 2.1.4 on 2019-01-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190111_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
