# Generated by Django 2.1.4 on 2019-01-11 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190111_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jiami',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
