# Generated by Django 2.1.4 on 2019-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190111_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='neirong',
            field=models.CharField(max_length=10000),
        ),
    ]
