# Generated by Django 2.1.4 on 2019-01-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190111_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanmus',
            name='lan_id',
        ),
        migrations.AddField(
            model_name='lanmus',
            name='alias',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lanmus',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lanmus',
            name='fid',
            field=models.CharField(default='无', max_length=150),
        ),
        migrations.AddField(
            model_name='lanmus',
            name='keywords',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AddField(
            model_name='lanmus',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
