# Generated by Django 2.1.4 on 2019-01-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190112_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanmus',
            name='lanmu',
        ),
    ]
