# Generated by Django 2.1.4 on 2019-01-14 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_lanmus_lanmu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanmus',
            name='lanmu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Lanmus'),
        ),
    ]
