# Generated by Django 2.1.4 on 2019-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_yonghu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='neirong',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
