# Generated by Django 2.1.4 on 2019-01-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190114_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(null=True, upload_to='upload')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='yonghu',
            name='icon',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
