# Generated by Django 2.1.4 on 2019-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190116_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanmus',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='share',
            table='share',
        ),
    ]
